name: dotfiles
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  install:
    runs-on: windows-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      run: Set-ExecutionPolicy Bypass -scope CurrentUser
    -
      name: Run the Installer
      run: .\install.ps1
